- hosts: all
  become: yes
  become_method: root

  tasks:
  - name: 1. install system updates for centos systems
    yum: name=* state=latest update_cache=yes
    when: ansible_distribution == "CentOS"


  - name: 2. Install wget Tools
    yum: name={{item}} state=installed
    with_items:
          - curl
          - wget

  - name: 3. Installed kubectl Repository
    shell: "{{item}}"
    with_items:
          - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
          - chmod +x ./kubectl
          - mv ./kubectl /usr/local/bin/kubectl

  - name: 4. Install Bash-completion
    yum: name=bash-completion styate=installed

  - name: 5. Intall Minikube Repository
    command: "{{item}}"
    with_items:
      - wget -O /etc/yum.repos.d/antonpatsev-minikube-rpm-epel-7.repo https://copr.fedorainfracloud.org/coprs/antonpatsev/minikube-rpm/repo/epel-7/antonpatsev-minikube-rpm-epel-7.repo
      - yum clean all
  - name: 6. install the required packages
    package:
      name: "{{ item }}"
      state: latest
    with_items: "{{ minikube_dependencies }}"
    minikube_dependencies:
      - python-lxml
      - python-libvirt
      - qemu-kvm
      - firewalld
      - libvirt
      - libvirt-daemon-system
      - libvirt-daemon-kvm
      - dnsmasq

  - name: 7. start services
    service:
      name: "{{ item }}"
      state: restarted
      enabled: yes
    with_items:
      - firewalld
      - libvirtd

  - name: 8. Install Minikube From Yum Repository
    yum:  name=minikube  state=installed

  - name: 9. Started Minikube
    shell: "minikube start"
    notify: minikube start



  - name: 10. Running Test Nginx Test Pod
    command: "{{item}}"
    with_items:
          - kubectl run test-nginx --image=nginx --replicas=2 --port=80
